---
# If this one fails: check if exec-shield is found in sysctl.conf and remove it
# It has been removed with/in RHEL/CentOS 7
# https://access.redhat.com/solutions/974563
- name: enable ipv4 forwarding for docker usage
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present

- name: create maxscale config
  template:
    src: maxscale.cnf.j2
    dest: "{{ maxscale_config_file_path }}"
    mode: 0644

- name: start maxscale docker container
  docker_container:
    name: maxscale
    image: "mariadb/maxscale:{{ maxscale_docker_version | default('latest') }}"
    state: "{{ maxscale_docker_state | default('started') }}"
    restart: "{{ maxscale_docker_restart | default('false') }}"
    pull: "{{ maxscale_docker_pull_image | default('false') }}"
    recreate: "{{ maxscale_docker_recreate | default('false') }}"
    restart_policy: always
    restart_retries: 3
    ports:
      - "{{ maxscale_admin_port }}:{{ maxscale_admin_port }}"
      - "{{ item.port }}:{{ item.port }}"
    volumes:
      - "{{ maxscale_config_file_path }}:/etc/maxscale.cnf"
  loop: "{{ maxscale_config_listener_list }}"
